"""
bookmaker_ratings.py
Comprehensive bookmaker directory with reliability ratings,
account creation guidance, and NZ passport compatibility.
"""

BOOKMAKER_RATINGS = {
    "Pinnacle": {
        "rating": 5,
        "label": "Arb Friendly",
        "color": "#34d399",
        "icon": "✅",
        "note": "The gold standard for arb bettors. Welcomes sharp money, almost never limits accounts.",
        "limits_arbers": False,
        "country": "Curacao",
        "currency": "USD, EUR, GBP",
        "nz_passport": True,
        "nz_note": "Accepts international players. NZ passport accepted. Available in most countries except US.",
        "vpn_risk": "Low",
        "signup_url": "pinnacle.com",
        "min_deposit": "$10",
        "highlights": "Best odds in the industry. No maximum win limits. Ideal first account for arb bettors.",
        "watchouts": "No bonus offers. Interface can feel dated. Withdrawal fees on some methods.",
    },
    "Betfair": {
        "rating": 5,
        "label": "Arb Friendly",
        "color": "#34d399",
        "icon": "✅",
        "note": "Betting exchange — you bet against other users, not the house. No incentive to limit winners.",
        "limits_arbers": False,
        "country": "United Kingdom",
        "currency": "GBP, EUR, AUD, USD",
        "nz_passport": True,
        "nz_note": "Accepts NZ players via Betfair Australia (AUD) or international site (GBP). NZ passport accepted.",
        "vpn_risk": "Low",
        "signup_url": "betfair.com",
        "min_deposit": "$10",
        "highlights": "Exchange model means you get the best possible odds. No account restrictions for winners.",
        "watchouts": "5% commission on net winnings. Liquidity can be low on minor markets.",
    },
    "Matchbook": {
        "rating": 5,
        "label": "Arb Friendly",
        "color": "#34d399",
        "icon": "✅",
        "note": "Betting exchange with very low commission (1-2%). Excellent for arbing.",
        "limits_arbers": False,
        "country": "United Kingdom",
        "currency": "GBP, EUR, USD",
        "nz_passport": True,
        "nz_note": "Accepts international players. NZ passport accepted for verification.",
        "vpn_risk": "Low",
        "signup_url": "matchbook.com",
        "min_deposit": "$10",
        "highlights": "Lower commission than Betfair. Good liquidity on major sports.",
        "watchouts": "Smaller market selection than Betfair. Less liquidity on minor leagues.",
    },
    "Smarkets": {
        "rating": 5,
        "label": "Arb Friendly",
        "color": "#34d399",
        "icon": "✅",
        "note": "Betting exchange with flat 2% commission. No account restrictions for winners.",
        "limits_arbers": False,
        "country": "United Kingdom",
        "currency": "GBP, EUR",
        "nz_passport": True,
        "nz_note": "Accepts international players. NZ passport accepted. Verify using passport + proof of address.",
        "vpn_risk": "Low",
        "signup_url": "smarkets.com",
        "min_deposit": "$10",
        "highlights": "Clean interface. Flat 2% commission. Good for soccer and politics markets.",
        "watchouts": "Smaller than Betfair. US and some other markets restricted.",
    },
    "Unibet": {
        "rating": 3,
        "label": "Moderate Risk",
        "color": "#fbbf24",
        "icon": "⚠️",
        "note": "Generally tolerant but will limit accounts showing consistent arb patterns.",
        "limits_arbers": True,
        "country": "Malta / Sweden",
        "currency": "GBP, EUR, AUD, SEK",
        "nz_passport": True,
        "nz_note": "NZ players accepted on international site. Passport accepted for KYC verification.",
        "vpn_risk": "Medium",
        "signup_url": "unibet.com",
        "min_deposit": "$10",
        "highlights": "Wide market selection. Good mobile app. Competitive odds on major sports.",
        "watchouts": "Will limit accounts over time. VPN may trigger fraud checks on deposit.",
    },
    "1xBet": {
        "rating": 3,
        "label": "Moderate Risk",
        "color": "#fbbf24",
        "icon": "⚠️",
        "note": "High odds but withdrawal issues reported. Use with caution and keep balances low.",
        "limits_arbers": True,
        "country": "Curacao",
        "currency": "USD, EUR, and 50+ others",
        "nz_passport": True,
        "nz_note": "Accepts almost all countries. NZ passport accepted. However, regulatory oversight is minimal.",
        "vpn_risk": "Low",
        "signup_url": "1xbet.com",
        "min_deposit": "$1",
        "highlights": "Huge market selection. Very high odds. Accepts crypto. Available almost everywhere.",
        "watchouts": "Withdrawal delays common. Weak regulatory oversight. Do not keep large balances here.",
    },
    "Coolbet": {
        "rating": 3,
        "label": "Moderate Risk",
        "color": "#fbbf24",
        "icon": "⚠️",
        "note": "Estonian operator with decent odds. Moderate arb tolerance.",
        "limits_arbers": True,
        "country": "Estonia",
        "currency": "EUR",
        "nz_passport": False,
        "nz_note": "Primarily serves European markets. NZ players may struggle with verification. VPN likely needed.",
        "vpn_risk": "High",
        "signup_url": "coolbet.com",
        "min_deposit": "$10",
        "highlights": "Sharp odds. Good for European sports. Clean interface.",
        "watchouts": "Primarily EU-focused. Account creation difficult without EU address. EUR only.",
    },
    "Nordic Bet": {
        "rating": 3,
        "label": "Moderate Risk",
        "color": "#fbbf24",
        "icon": "⚠️",
        "note": "Scandinavian bookmaker. Reasonable tolerance but will limit large or frequent winners.",
        "limits_arbers": True,
        "country": "Malta / Denmark",
        "currency": "EUR, DKK, SEK, NOK",
        "nz_passport": False,
        "nz_note": "Primarily Scandinavian market. NZ accounts difficult — requires European address for full verification.",
        "vpn_risk": "High",
        "signup_url": "nordicbet.com",
        "min_deposit": "$10",
        "highlights": "Good odds on Scandinavian leagues. Competitive on major European football.",
        "watchouts": "Geo-restricted outside Scandinavia. NZ passport likely insufficient without EU proof of address.",
    },
    "MyBookie.ag": {
        "rating": 3,
        "label": "Moderate Risk",
        "color": "#fbbf24",
        "icon": "⚠️",
        "note": "US-facing offshore book. Decent odds but account reviews for winners are common.",
        "limits_arbers": True,
        "country": "Curacao",
        "currency": "USD",
        "nz_passport": True,
        "nz_note": "Offshore book accepting international players. NZ passport accepted for ID verification.",
        "vpn_risk": "Low",
        "signup_url": "mybookie.ag",
        "min_deposit": "$50",
        "highlights": "USD-based. Good for US sports. Accepts crypto deposits.",
        "watchouts": "Slow withdrawals. Primarily US sports focused. Customer service can be slow.",
    },
    "BetVictor": {
        "rating": 2,
        "label": "High Risk",
        "color": "#f87171",
        "icon": "🚨",
        "note": "Known to limit winning accounts. Keep stakes natural-looking.",
        "limits_arbers": True,
        "country": "Gibraltar / Malta",
        "currency": "GBP, EUR, USD",
        "nz_passport": True,
        "nz_note": "Accepts international players. NZ passport accepted for KYC. Some geo-restrictions apply.",
        "vpn_risk": "Medium",
        "signup_url": "betvictor.com",
        "min_deposit": "$10",
        "highlights": "Competitive odds. Good market depth on soccer and racing.",
        "watchouts": "Aggressive account limiting for winners. Expect restrictions within weeks of consistent winning.",
    },
    "Bet365": {
        "rating": 1,
        "label": "Limit Risk",
        "color": "#f87171",
        "icon": "🚨",
        "note": "Aggressively limits arb bettors. Expect stake restrictions after consistent wins.",
        "limits_arbers": True,
        "country": "United Kingdom",
        "currency": "GBP, EUR, AUD, USD, NZD",
        "nz_passport": True,
        "nz_note": "Fully accepts NZ players with NZD accounts. NZ passport standard for verification. No VPN needed.",
        "vpn_risk": "Low",
        "signup_url": "bet365.com",
        "min_deposit": "$10",
        "highlights": "Accepts NZD. Best in-play betting. Huge market selection. Easiest account to open from NZ.",
        "watchouts": "Most aggressive bookmaker for limiting arb bettors. Expect limits within 1-2 months.",
    },
    "William Hill": {
        "rating": 1,
        "label": "Limit Risk",
        "color": "#f87171",
        "icon": "🚨",
        "note": "Frequently restricts accounts. Keep stakes modest.",
        "limits_arbers": True,
        "country": "United Kingdom",
        "currency": "GBP, EUR",
        "nz_passport": False,
        "nz_note": "Primarily UK/European market. NZ players generally not accepted on main site. Try William Hill Australia.",
        "vpn_risk": "High",
        "signup_url": "williamhill.com",
        "min_deposit": "$10",
        "highlights": "Large market selection. Established brand. Good for UK sports.",
        "watchouts": "Not easily accessible from NZ. Strong account limiting policy.",
    },
    "Betway": {
        "rating": 2,
        "label": "High Risk",
        "color": "#f87171",
        "icon": "🚨",
        "note": "Restricts winning accounts. Arb activity is monitored closely.",
        "limits_arbers": True,
        "country": "Malta",
        "currency": "GBP, EUR, USD",
        "nz_passport": True,
        "nz_note": "International site accepts NZ players. NZ passport accepted for verification.",
        "vpn_risk": "Medium",
        "signup_url": "betway.com",
        "min_deposit": "$10",
        "highlights": "Clean interface. Good mobile app. Wide sport coverage.",
        "watchouts": "Known to limit winners. Withdrawal process can be slow first time.",
    },
    "PlayUp": {
        "rating": 3,
        "label": "Moderate Risk",
        "color": "#fbbf24",
        "icon": "⚠️",
        "note": "Australian operator. Moderate tolerance, watch for stake restrictions.",
        "limits_arbers": True,
        "country": "Australia",
        "currency": "AUD",
        "nz_passport": True,
        "nz_note": "Australian-licensed. NZ players accepted. NZ passport accepted for full KYC verification.",
        "vpn_risk": "Low",
        "signup_url": "playup.com.au",
        "min_deposit": "A$10",
        "highlights": "AUD-based. Good for Australian and NZ players. Strong on racing and rugby.",
        "watchouts": "Primarily Australian sports focus. Limited European market depth.",
    },
    "Unibet (NL)": {
        "rating": 3,
        "label": "Moderate Risk",
        "color": "#fbbf24",
        "icon": "⚠️",
        "note": "Dutch-licensed Unibet. Similar profile to main Unibet.",
        "limits_arbers": True,
        "country": "Netherlands",
        "currency": "EUR",
        "nz_passport": False,
        "nz_note": "Dutch gambling licence — requires Dutch residency for full account. Not recommended for NZ players.",
        "vpn_risk": "Very High",
        "signup_url": "unibet.nl",
        "min_deposit": "€10",
        "highlights": "Good odds on European markets.",
        "watchouts": "Dutch residency required. NZ passport insufficient. Skip this one.",
    },
}

DEFAULT_RATING = {
    "rating": 3,
    "label": "Unknown",
    "color": "#64748b",
    "icon": "❓",
    "note": "No data available for this bookmaker.",
    "limits_arbers": None,
    "country": "Unknown",
    "currency": "Unknown",
    "nz_passport": None,
    "nz_note": "No account information available.",
    "vpn_risk": "Unknown",
    "signup_url": "",
    "min_deposit": "Unknown",
    "highlights": "",
    "watchouts": "",
}


def get_rating(bookmaker_name):
    for key, val in BOOKMAKER_RATINGS.items():
        if key.lower() == bookmaker_name.lower():
            return val
    return DEFAULT_RATING


def get_opportunity_risk_score(bookmakers):
    ratings = [get_rating(b) for b in bookmakers]
    min_rating = min(r["rating"] for r in ratings)
    worst = bookmakers[ratings.index(min(ratings, key=lambda r: r["rating"]))]
    if min_rating >= 4:
        advice = "Low risk — both books are arb-friendly."
        color = "#34d399"
    elif min_rating == 3:
        advice = "Moderate risk — vary your stakes and timing to avoid detection."
        color = "#fbbf24"
    else:
        advice = "High risk — at least one book is known to limit arb bettors. Keep stakes natural."
        color = "#f87171"
    return {
        "overall_rating": min_rating,
        "worst_book": worst,
        "advice": advice,
        "color": color,
    }
